FROM python:3.10-alpine

WORKDIR /app


COPY dock.txt .

RUN pip install --no-cache-dir --only-binary=:all: -r dock.txt

COPY . .

EXPOSE 8080

CMD ["uvicorn", "spaceship.main:app", "--host=0.0.0.0", "--port=8080"]